[project]
name = "gpt4o-strange-chinese-tokens"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "openai>=1.55.0",
    "pandas>=2.2.3",
    "regex>=2024.11.6",
    "tabulate>=0.9.0",
    "tiktoken>=0.8.0",
]
package-mode = false
